In [ ]:
from nba_api.stats.endpoints import leaguedashplayerstats, playercareerstats

In [ ]:
df_season2023_24 = leaguedashplayerstats.LeagueDashPlayerStats(
    season='2023-24',
    season_type_all_star='Regular Season'
).get_data_frames()[0]

print(df_season2023_24.shape)
print(df_season2023_24.columns.tolist())

(572, 67)
['PLAYER_ID', 'PLAYER_NAME', 'NICKNAME', 'TEAM_ID', 'TEAM_ABBREVIATION', 'AGE', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS', 'NBA_FANTASY_PTS', 'DD2', 'TD3', 'WNBA_FANTASY_PTS', 'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'FGM_RANK', 'FGA_RANK', 'FG_PCT_RANK', 'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK', 'FTM_RANK', 'FTA_RANK', 'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK', 'REB_RANK', 'AST_RANK', 'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK', 'PF_RANK', 'PFD_RANK', 'PTS_RANK', 'PLUS_MINUS_RANK', 'NBA_FANTASY_PTS_RANK', 'DD2_RANK', 'TD3_RANK', 'WNBA_FANTASY_PTS_RANK', 'TEAM_COUNT']

In [ ]:
df_min = df_season2023_24[df_season2023_24["TEAM_ABBREVIATION"]== 'MIN']
df_min.head()

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,TEAM_COUNT
29,1630162,Anthony Edwards,Anthony,1610612750,MIN,22.0,79,54,25,0.684,...,517,452,20,6,11,12,64,38,11,1
105,1630227,Daishen Nix,Daishen,1610612750,MIN,22.0,15,11,4,0.733,...,121,29,485,490,168,506,257,38,500,1
225,1630183,Jaden McDaniels,Jaden,1610612750,MIN,23.0,72,48,24,0.667,...,393,559,176,153,82,170,257,38,171,1
296,1629162,Jordan McLaughlin,Jordan,1610612750,MIN,28.0,56,35,21,0.625,...,166,176,339,346,83,321,257,38,328,1
305,1631169,Josh Minott,Josh,1610612750,MIN,21.0,32,23,9,0.719,...,121,95,446,448,189,460,257,38,458,1

In [ ]:
df_top10_s24 = df_season2023_24[df_season2023_24["PTS_RANK"] <= 10].sort_values(by='PTS_RANK',ascending=True)
df_top10_s24.head(10)

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,TEAM_COUNT
372,1629029,Luka Dončić,Luka,1610612742,DAL,25.0,70,46,24,0.657,...,497,475,4,1,32,2,6,3,1,1
501,1628983,Shai Gilgeous-Alexander,Shai,1610612760,OKC,25.0,75,55,20,0.733,...,556,529,2,2,3,6,73,38,5,1
184,203507,Giannis Antetokounmpo,Giannis,1610612749,MIL,29.0,73,45,28,0.616,...,565,555,1,3,29,3,4,4,3,1
233,1628973,Jalen Brunson,Jalen,1610612752,NYK,27.0,77,49,28,0.636,...,531,463,2,4,6,11,64,38,9,1
434,203999,Nikola Jokić,Nikola,1610612743,DEN,29.0,79,55,24,0.696,...,541,542,6,5,1,1,2,2,2,1
29,1630162,Anthony Edwards,Anthony,1610612750,MIN,22.0,79,54,25,0.684,...,517,452,20,6,11,12,64,38,11,1
337,201142,Kevin Durant,Kevin,1610612756,PHX,35.0,75,44,31,0.587,...,495,435,14,7,38,9,47,16,8,1
268,1628369,Jayson Tatum,Jayson,1610612738,BOS,26.0,74,57,17,0.770,...,526,465,19,8,4,10,22,38,7,1
125,1628368,De'Aaron Fox,De'Aaron,1610612758,SAC,26.0,74,42,32,0.568,...,541,540,21,9,52,13,93,38,13,1
509,201939,Stephen Curry,Stephen,1610612744,GSW,36.0,74,43,31,0.581,...,499,400,36,10,66,23,84,38,14,1

In [14]:
df_season2024_25 = leaguedashplayerstats.LeagueDashPlayerStats(
    season='2024-25',
    season_type_all_star='Regular Season'
).get_data_frames()[0]

print(df_season2024_25.shape)
print(df_season2024_25.columns.tolist())

(569, 67)
['PLAYER_ID', 'PLAYER_NAME', 'NICKNAME', 'TEAM_ID', 'TEAM_ABBREVIATION', 'AGE', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS', 'NBA_FANTASY_PTS', 'DD2', 'TD3', 'WNBA_FANTASY_PTS', 'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'FGM_RANK', 'FGA_RANK', 'FG_PCT_RANK', 'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK', 'FTM_RANK', 'FTA_RANK', 'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK', 'REB_RANK', 'AST_RANK', 'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK', 'PF_RANK', 'PFD_RANK', 'PTS_RANK', 'PLUS_MINUS_RANK', 'NBA_FANTASY_PTS_RANK', 'DD2_RANK', 'TD3_RANK', 'WNBA_FANTASY_PTS_RANK', 'TEAM_COUNT']

In [15]:
df_top10_s25 = df_season2024_25[df_season2024_25["PTS_RANK"] <= 10].sort_values(by="PTS_RANK", ascending=True)
df_top10_s25.head(10)

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,TEAM_COUNT
490,1628983,Shai Gilgeous-Alexander,Shai,1610612760,OKC,26.0,76,63,13,0.829,...,561,511,2,1,1,2,93,44,2,1
29,1630162,Anthony Edwards,Anthony,1610612750,MIN,23.0,79,48,31,0.608,...,523,480,10,2,46,6,87,44,3,1
423,203999,Nikola Jokić,Nikola,1610612743,DEN,30.0,70,46,24,0.657,...,540,505,4,3,2,1,2,1,1,1
180,203507,Giannis Antetokounmpo,Giannis,1610612749,MIL,30.0,67,40,27,0.597,...,559,496,1,4,28,3,5,2,4,1
263,1628369,Jayson Tatum,Jayson,1610612738,BOS,27.0,72,53,19,0.736,...,526,498,16,5,7,5,18,15,6,1
141,1626164,Devin Booker,Devin,1610612756,PHX,28.0,75,35,40,0.467,...,538,552,7,6,507,14,35,44,11,1
523,1629027,Trae Young,Trae,1610612737,ATL,26.0,76,36,40,0.474,...,546,469,3,7,167,7,6,44,7,1
540,1629639,Tyler Herro,Tyler,1610612748,MIA,25.0,77,37,40,0.481,...,555,307,47,8,112,17,71,44,12,1
69,1630595,Cade Cunningham,Cade,1610612765,DET,23.0,70,38,32,0.543,...,568,550,23,9,78,9,18,5,8,1
241,201935,James Harden,James,1610612746,LAC,35.0,79,50,29,0.633,...,543,506,8,10,24,4,11,11,5,1